import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import DefaultLayout from './DefaultLayout'
import AuthProvider from './context/AuthProvider'
import { CartContextProvider } from './context/useCart'
import { CartProvider } from './provider/CartProvider'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster toastOptions={{
          style: {
            background: "rgb(51 65 85)",
            color:"#fff"
          }
        }}/>
        <AuthProvider>
        <CartProvider>
        <DefaultLayout>
          {children}
          </DefaultLayout>
         
        </CartProvider>
         
          
         
           
        </AuthProvider>
      
        
        
        </body>
    </html>
  )
}
